version: '3'
services:
 
  react_native_app:
    build:
      context: .
      dockerfile: Dockerfile.react-native
    ports:
      - "5000:5000"

 
  node_backend:
    build:
      context: .
      dockerfile: Dockerfile.node-backend
    ports:
      - "3000:3000"
  


